const cources = [
  {
    name: "ADIT",
    subjects: [
      "Basic Concept of Computer",
      "Windows 7, 10 & 11",
      "MS Office 07, 10 &13",
      "Tally with GST",
      "Accounts with Inventory",
      "Desk Top Inventory",
      "Photoshop CS",
      "Corel Draw X7",
      "Create Logo in Corel",
      "Typing Hindi & English",
      "Project Reports",
      "Job Placement training",
      "Internet & E-mail",
    ],
    duration: "12 Months",
  },
  {
    name: "DCA",
    subjects: [
      "Basic Concept of Computer",
      "Windows 7, 10 & 11",
      "MS Office 10",
      "Tally with GST",
      "Accounts with Inventory",
      "Typing Hindi & English",
      "Project Reports",
      "Job Placement training",
      "Internet & E-mail",
    ],
    duration: "06 Months",
  },
  {
    name: "CCC",
    subjects: [
      "Basic Concept of Computer",
      "Windows 7, 10 & 11",
      "Libre Office",
      "Writer, Cale, Impress",
      "Typing",
      "Job Placement training",
      "Internet & E-mail",
    ],
    duration: "03 Months",
  },
];
export default cources;
